// To add a product: copy one object below, change the text, and give it a new unique id.
export const PRODUCTS = [
  {
    id: "repo-reader",
    num: "01",
    kind: "Developer tool · AI",
    name: "Repo Reader",
    alt: "repo-reader · Web app",
    stack: "FastAPI · React · Groq · Supabase",
    short: "Paste a public GitHub repo and get an architecture diagram, a plain-English description, and a technical explanation of how the code works.",
    what: "Repo Reader reads every code file in a public GitHub repository and turns it into a labeled architecture diagram, a plain-English project description, and a technical explanation of how the code fits together.",
    who: "Students, interviewers, and developers who need to understand an unfamiliar codebase quickly.",
    steps: [
      "Paste a public GitHub link.",
      "The backend downloads the repo and maps modules, imports, API calls, data models, and external services.",
      "An AI model writes the description and explanation from those facts only, so nothing is invented.",
      "Download the diagram as PNG or SVG.",
    ],
    tech: "FastAPI, React, Mermaid, Groq, Supabase, Razorpay.",
    url: "https://reporeader.products.chandanmhj.in",
    cta: "Launch Repo Reader ↗",
  },
  {
    id: "csv-reader",
    num: "02",
    kind: "Data tool · AI",
    name: "CSV-Reader",
    alt: "csv-reader · Web app",
    stack: "FastAPI · React · Groq · Plotly",
    short: "Upload one or more CSV files and get clean data, readable column names, interactive charts, and a plain-English summary of what the data says.",
    what: "CSV-Reader takes one or more CSV files and turns them into a clear report. It fills or removes missing values, caps outliers instead of deleting rows, rewrites cryptic column names into readable ones, picks charts that suit your data, and explains the results in plain English.",
    who: "Students, analysts, and anyone with a spreadsheet who wants to understand it quickly without writing code.",
    steps: [
      "Upload one or more CSV files, up to 60 MB each, and drag from one column to another to link tables.",
      "The backend cleans the data, and you can review every choice and override it, such as delete instead of fill.",
      "An AI model picks the charts and writes the summary from the calculated numbers only, so nothing is invented.",
      "Rename any column with the pen icon, click a bar to drill in, then download the charts as PNG or SVG.",
    ],
    tech: "FastAPI, pandas, LangGraph, Groq, Plotly, React. Uploaded files are deleted after 24 hours.",
    url: "https://csvreader.products.chandanmhj.in",
    cta: "Launch CSV-Reader ↗",
  },
];